name       : haskell-skylighting
version    : 0.7.1
release    : 2
source     :
    - https://hackage.haskell.org/package/skylighting-0.7.1/skylighting-0.7.1.tar.gz : c0bcd4f0075c77226052ab9a04f90ff8d2f2c8e97e5083d9e65843635bb0f574
license    : GPL-2.0
component  : programming.haskell
summary    : Skylighting is a syntax highlighting library with support for over one hundred languages.
description: |
    Skylighting is a syntax highlighting library with support for over one hundred languages.
builddeps  :
    - haskell-cabal-install
    - haskell-skylighting-core
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
