name       : haskell-skylighting
version    : 0.8.5
release    : 3
source     :
    - https://hackage.haskell.org/package/skylighting-0.8.5/skylighting-0.8.5.tar.gz : 5ba30911f5718ec4c5e76d160c358892b301b3ea58d009cb0506dcabaf0615ad
license    : GPL-2.0-only
component  : programming.haskell
summary    : Skylighting is a syntax highlighting library with support for over one hundred languages.
description: |
    Skylighting is a syntax highlighting library with support for over one hundred languages.
builddeps  :
    - haskell-cabal-install
    - haskell-skylighting-core-devel
rundeps    :
    - devel:
        - haskell-skylighting-core-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
