name       : haskell-skylighting
version    : 0.1.1.5
release    : 1
source     :
    - https://hackage.haskell.org/package/skylighting-0.1.1.5/skylighting-0.1.1.5.tar.gz : 0a4b666b2ccfeed35386bd364d663e919adc1815547e6360e83487253e33b13c
license    : GPL-2.0
component  : programming.haskell
summary    : Skylighting is a syntax highlighting library with support for over one hundred languages.
description: |
    Skylighting is a syntax highlighting library with support for over one hundred languages.
builddeps  :
    - haskell-aeson
    - haskell-blaze-html
    - haskell-cabal-install
    - haskell-case-insensitive
    - haskell-hxt
    - haskell-pretty-show
    - haskell-regex-pcre-builtin
    - haskell-safe
    - haskell-utf8-string
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
